# Appendices {#appendices}

## 1. Statistical Analysis Plan (SAP)
Analysis Plan

Working Title:

Overview/Purpose:

General Scientific Question(s):

Specific Scientific Question(s) (e.g. hypotheses):

Outcomes of Interest:

Predictors of Interest:

Potential Confounders or Adjustment Variables:

Other Data Specifics (e.g. time period, subgroup):

Data request (date, number):

Type of Analysis:  		Hypothesis testing			Estimation
				Hypothesis screening			Modeling	
				Hypothesis generating/exploratory	Method evaluation
				Descriptive
Analysis Approach and Special Issues:

List of Tables:  (or note location of draft tables)

Plan of Action:

Responsibilities and deadlines:
	Paper outline
	Initial analyses
	Introduction
	Methods
	Results
	Discussion
	Tables and Figures
	Follow up analyses
	Final Draft

Names and roles (authors, co-authors, Data Core staff):

Revision History:


## 2. List of Acronyms and Abbreviations

- **CAP**: Criteria Air Pollutant
- **CC**: Coordinating Center
- **C-CAR**: Center for Clean Air Research
- **COOP**: Cooperative Station
- **CRAN**: Comprehensive R Archive Network
- **DMDA**: Data and Materials Distribution Agreement
- **EAC**: Exposure Assessment Core
- EC/OC – Elemental carbon and organic carbon
- **FIPS**: Federal Information Processing Standards
- **FRM**: Federal Reference Method
- **GIS**: Geographic Information System
- **HAP**: Hazardous Air Pollutant
- **HEI**: Health Effects Institute
- **IMPROVE**: Interagency Monitoring of Protected Visual Environments
- **LAC**: Light Absorption Coefficient
- **LOD**: Limit of Detection
- **MAIDS**: MESA Air Intermediate Data Server
- **MESA**: Multi-Ethnic Study of Atherosclerosis
- **µg/m3** – micrograms per cubic meter
- **NAAQS**: National Ambient Air Quality Standards
- **NEI**: National Emissions Inventory
- **NDVI**: Normalized Difference Vegetation Index
- **NIST**: National Institute of Standards and Technology
- **NO**: Nitrogen oxide
- **NOAA**: National Oceanic and Atmospheric Administration
- **NO2**: Nitrogen dioxide
- **NOX**: Oxides of nitrogen, including NO2 and NO
- **NPACT**: National Particle Components Toxicity
- **O3**: Ozone
- **PM**: Particulate matter
- **PM2.5** – Particulate matter <= 2.5 µg in diameter
- **PM10**: Particulate matter <= 10 µg in diameter
- **POC**: Parameter Occurrence Code
- **ppm**: parts per million
- **ppb**: parts per billion
- **QA**: Quality Assurance
- **QC**: Quality Control
- **S**: Sulfur
- **SAP**: Statistical Analysis Plan
- **Se**: Selenium
- **Si**: Silicon
- **SOP**: Standard Operating Procedure
- **SO2**: Sulfur dioxide
- **SPCS**: State Plane Coordinate System
- **STN**: Speciation Trends Network 
- **VOC**: Volatile Organic Compound
- **XRF**: X-ray fluorescence
- **WBAN**: Weather Bureau Army Navy
- WHI - **OS**: Women’s Health Initiative - Observational Study

## 3.  Referenced Documents and Code Locations

<!-- 
Referenced Documents
Description
Directory
Filename
Quality Assurance Project Plan (MESA Air)
M:\MAIDS\QA\QAPP\
QAPP_040709.doc
Final QA/QC Report 
(MESA Air)
M:\MAIDS\QA\QA report for ESAC\
QAQC_Committee_Report_
042310.doc
Metadata document
M:\MAIDS\Documentation\GIS\Metadata
Metadata_08042009.doc
Field SOPs
M:\MAIDS\QA\SOPs\Field\
Final\ Current SOPs\PDFs
All documents in directory
Lab SOPs
M:\MAIDS\QA\SOPs\Labs\
Final\PDFs

All documents in directory
Documentation of MESA Air Implementation of CALINE3QHR Model
CALINEDoc2.doc
Subversion repository, ExposureModel\CALINE\
Monitor Issue Log
M:\MAIDS\QA\AQS_QA
Monitor_Issue_Log.xls
QA/QC Report 
(SPIROMICS Air)
P:\QA\QA_report
QAQC_report_14July16.docx 
(in progress)
QA/QC Report (CCAR)
W:\UW CCAR\Project 1-5, Cores Folders\Project 5\QC\QAQC_report

QMP (CCAR)
W:\UW CCAR\QA QC
Quality Management Plan
QA/QC Report (Coarse)



Useful scripts and codefiles
Purpose
Filename
Language
Directory
Parses pump files for TSI Sidepack 530 pumps
get_pump_data.sas

H:\ My Documents\sas_code
Reads and processes HOBO files for indoor temperature and relative humidity
get_hobo_data.sas

H:\ My Documents\sas_code
Removes duplicate road segments from TeleAtlas shapefiles
cat_and_dedup_roads.py
Python
H:\GIS\pycode\mesa\
Calculates covariates for point locations
covar.py
Python
H:\GIS\pycode\mesa\
Parses AQS ‘input transaction’ formatted files for monitors
ReadAQS_Monitors.sas

M:\MAIDS\
EPA monitoring\Programs
Parses AQS concentration files
ReadAQS_NO2.sas
ReadAQS_Nox.sas
ReadAQS_PM25.sas

Subversion repository, Data_Processing_Codes\
MesaAQS_Raw directory
Read in and combine data tables in the NEI database
Read Sources.sas

M:\MAIDS\Emissions Data\Programs\
Parses and formats raw temperature and humidity data 
ReadMet.sas

M:\MAIDS\MeteorologicalData\
Programs
Nearest Monitor Calculation
nearest.R

Subversion repository, ExposureModel\ SimpleModels\
Updates metadata table
metadata_tbl.py
Python
Q:\eac_database\code
Creates request folder
make_request.sh
Bash
Q:\eac_database\requests
Generates data request datasets and metadata
fill_request.sh
Bash
Q:\eac_database\requests


Locations of raw monitoring data
Contents
Filename
Directory
Field log data
MESA_Samples_V1_2008_10_10.mdb
M:\MAIDS\COC
Teflon mass measurements
MESA_Air_FilterMassEntry_v1_2.mdb
M:\MAIDS\GravLACAnalysis\database
Teflon LAC measurements
MESA_Air_Reflectometry_v1_1.mdb
M:\MAIDS\GravLACAnalysis\database
Ion Chromatography measurements for Ogawas (NO2, SO2, and O3)
IC<YYYMMDD_##>.xls
M:\MAIDS\AnalyticLab\Edited IC Data for Import Jim
Ultraviolet Spectroscopy (For NOX)
UV<YYYMMDD_##>.xls
M:\MAIDS\AnalyticLab \Edited UV Data for Import Jim
Infiltration questionnaire
InfiltrationObservaton_v_1_09_10_08.mdb
M:\MAIDS\Field\Databases
Time Activity Diary for personal sampling
TimeActivity_v_3.0.mdb
M:\MAIDS\Field\Databases
Chain of Custody (sample handling and shipping history)
MESA_Samples_V1_2008_10_10.mdb
M:\MAIDS\COC

-->

## 4.  Suggested Citations

<!--
Data Description
Suggested Citation
Airport and point source emission volumesa
USEPA, Emission Inventory Group, 2002 National Emissions Inventory Database [digital data set] (2006). U.S. Environmental Protection Agency: Washington, DC.  Available FTP: http://www.epa.gov/ttn/chief/net/2002inventory.html [accessed Aug 2008]. 
Road, railroad, railyard, and airport locations, coastlines
TeleAtlas, TeleAtlas Dynamap 2000 [CD_ROM] (2000). TeleAtlas, Lebanon, NH.
Population density
U.S. Department of Commerce, Census Bureau, TIGER/Line Shapefiles (2001).  U.S. Department of Commerce, Census Bureau: Washington, DC.  Available FTP: http://arcdata.esri.com/data/tiger2000/tiger_download.cfm, redistributed by TeleAtlas Dynamap 2000 [CD_ROM] (2000). TeleAtlas, Lebanon, NH. 
Land use
Price, C.V., Nakagaki, N., Hitt, K.J., and Clawges, R.C., Enhanced Historical Land-Use and Land-Cover Data Sets of the U.S. Geological Survey, U.S. Geological Survey Digital Data Series 240 [digital data set] (2006). Available: http://pubs.usgs.gov/ds/2006/240 [accessed Jun 2009].
Port locations and characteristicsb
National Imagery and Mapping Agency (NIMA), Ports of the Wider Caribbean, from NIMA World Port Index (2002). Distributed by the World Resources Institute: Washington, DC.  Available FTP: http://164.214.12.145/pubs/pubs_j_wpi_sections.html [accessed Jun 2009].
EPA AQS data
USEPA, Air Quality System Data: Query AQS Data [digital data set] (2011).  U.S. Environmental Protection Agency: Washington, DC.  Available: http://www.epa.gov/ttn/airs/airsaqs/detaildata/downloadaqsdata.htm [accessed June 2013].
Meteorological data
National Climatic Data Center, Hourly Global Surface Data [digital data set] (2010).  National Climatic Data Center: Asheville, NC.  Available: http://www7.ncdc.noaa.gov/CDO/dataproduct [accessed June 2013]. 
NDVIa
Carroll, M.L., C.M. DiMiceli, R.A. Sohlberg, and J.R.G. Townshend, 250m MODIS Normalized Difference Vegetation Index  [digital data set] (2008). University of Maryland, College Park, Maryland. All available days, 2006. Available: http://glcf.umiacs.umd.edu/data/ndvi/.
NYCCAS Data
The New York City Department of Health and Mental Hygiene, Queens College Center for the Biology of Natural Systems, and Zev Ross Spatial Analysis.
U.S. Census Data
Census 2000 Summary File 3—United States/ prepared by the U.S. Census Bureau, 2002.
U.S. Truck Routes
National Transportation Atlas Database [digital data set] (2009).  Bureau of Transportation Statistics: Washington, DC.  Available: http://www.bts.gov/publications/national_transportation_atlas_database.
NY Bus Routes
Quodomine, R. 2013. Personal communication (email with E. Spalt, 
University of Washington). New York Department of Transportation, 
Albany, NY.
Impervious Surface
NLCD 2006 Percent Developed Imperviousness [digital data set] (2006).  Multi-Resolution Land Characteristics Consortium: Sioux Falls, SD.  Available: http://ims.cr.usgs.gov/webappcontent/mrlc/nlcd2006_downloads.php.

Suggested citations, continued
MESA Air Monitoring Method
Cohen, Martin A., Adar, Sara D., Allen, Ryan W., Avol, Edward, Curl, Cynthia L., Gould, Timothy, Hardie, David, Ho, Anne, Kinney, Patrick, Larson, Timothy V., Sampson, Paul, Sheppard, Lianne, Stukovsky, Karen D., Swan, Susan S., Liu, L.-J. Sally, Kaufman, Joel D.,  Approach to Estimating Participant Pollutant Exposures in the Multi-Ethnic Study of Atherosclerosis and Air Pollution (MESA Air).  Environmental Science & Technology 2009, 43 (13), 4687-4693.
a This link no longer works or this exact file is no longer available online.  Please refer to table 10 for current links.
b This file is no longer available online, and the National Imagery and Mapping Agency no longer exists.  The current version (the Twentieth Edition) is produced by the National Geospatial Intelligence Agency.

-->

## 5.  Known Data Quality Issues

Issue
Extent of Data Affected
Expected Resolution
Overlapping polygons in land use shapefiles (>100% land use totals)
Locations along the coast of NC (primarily Sisters and WHI locations)
Manually fix shapefiles
Because the Oregon truck routes were determined by a different method than the rest of the US, truck route line lengths are doubled along A1 highways
Locations near A1 highways in Oregon (i.e. Sisters, WHI, AQS monitors)
Manually fix shapefiles
Distance to city hall calculations not correctly implemented in psql

--> 


## 6.  Quick Reference for Averaged Exposure Variable Names

Analysts may consider exposure periods ranging from a single day or week prior to an exam up to a number of years.  Some may consider multiple exposure periods.  Standard naming conventions help distinguish these different exposure periods quickly and easily.  The set formats for these variable names are:

- ` <pollutant>_<model>_<t1>_<t2>_<interval>_<reference>_<weighting>`
- `<pollutant>_<model>_<e1>_<e2>_<rounding>_<reference>_<weighting>`
- `<pollutant>_<model>_<yymm1>_<yymm2>_<weighting>`
- `<pollutant>_<model>_year_<year>_<weighting>`
- `MET_<meteorology>_<t1>_<t2>_<interval>_<reference>_<weighting>`

A table of the options that appear between brackets is included below.   Characters without brackets appear as literals.

Pollutants include all of the gases, elements, and PM sizes that have been mentioned throughout this document.  Models include both very sophisticated spatio-temporal models as well as ‘simple’ models such as ‘nearest monitor’ for PM2.5.  The numbers t1 and t2 indicate the span of the averaging period, while ‘interval’ indicates the units of time to which t1 and t2 refer.  Much of time, analysts are interested in a particular event, such as an exam, a stroke, or a diagnosis of disease.  This is the reference point.  Finally, some analysts will need the exposure averaged or weighted by the locations where participants actually lived.  Others will need the average at a particular location over the entire time period, regardless of whether the participant lived at that location during the entire time period.  Meteorological measurements can be averaged over similar time frames and will have similar names to indicate the averaging period.  However, ‘weighting’ will not be indicated, as there is only one meteorological time series in each study area.

<!--
Table of parameter options
Pattern Code
Description
Values
Meaning
pollutant
Pollutant of interest
PM25, PM10, Si, S, EC, OC, NOx, NO2, O3, etc.

model
Pollution model type
prag
lik
nat
acute
near
pragmatic
likelihood
national (long term)
acute regional time series
nearest monitor
meteorology
Meteorological variable
temp
rh
windspd
winddir
temperature
humidity
wind speed
wind direction
t1, t2
Timepoints that define beginning and end of the exposure averaging period
Integers from 0 – 99
“a” followed by an integer 1-99
Intervals before reference
Intervals after reference
e1, e2
Exam numbers
integer 1-6
Exam numbers between which average is calculated 
rounding
Whether time between exams is rounded to nearest whole year
rnd
trc
N/A
Round (nearest whole)
Truncate (round down)
Exact time
interval
Units of time
dy
wk
qt
yr
Day
week
quarter
year
reference
Reference point, or event that defines what the exposure is prior to
enrol
event
exam
ct
us
mri
enrollment
event (MI, stroke, diagnosis)
clinic exam 
weighting
Indicates whether the average is weighted over all addresses at which participants lived during the exposure period
wght
stat

wsp
statsp
weighted by all addresses
static, usually refers to ‘at exam’ address
weighted, spatial-only model
static, spatial-only model
yymm1, yymm2
Fixed endpoints of exposure period
0001 – 1112
two-digit year and two-digit month (beginning of month in endpoint 1 through end of month in endpoint 2)

-->


# 1.  MESA Air Modeling Regions

## H.  Ozone Modeling Regions


## I.  Performance Statistics for Exposure Models

**Table 27. Cross-validation measures of predictive accuracy for site means at monitoring locations for likelihood-based exposure models of NO2, NOx, PM2.5, and LAC.  Leave-one-out cross-validation was used for AQS and fixed sites and ten-fold cross-validation was used for home sites.  New York models include NYCCAS reference sites with AQS and fixed sites and NYCCAS distributed sites with home sites. Units for RMSE are ppb (NO2 and NOX), µg/m3 (PM2.5), and 10-5m-1 (LAC). R2reg represents the regression R2. Table taken from Keller et al.21**

**Table 28. Number of monitors and cross-validated measures of predictive accuracy for exposure models of NO2, NOx, PM2.5, and O3 for SPIROMICS Air. Leave-one-out cross-validation was used for AQS and fixed sites and ten-fold cross-validation was used for home sites.**



**Table 29. Model Performance using Cross Validation at AQS+Fixed Sites for O3 Spatio-Temporal Models.**



<!--
1. Leave one out cross validation (LOOCV) at AQS and fixed locations;
2. Median CVMSE and CVREG R2 based on annual averages at each AQS and fixed location across years, which reflects spatial prediction ability of the models;
3. Median CVMSE and CVREG R2 between predictions and observations at two-week time points across the entire study period for individual sites.
4. Los Angeles basin including Los Angeles and Riverside
5. Winston-Salem
-->





























**Table 29. Number of monitors and cross-validated measures of long-term predictive accuracy for exposure models of NO2, NOx, PM2.5, and O3 for the “omnibus” models combining MESA Air and SPIROMICS Air. Leave-one-out cross-validation was used for AQS and fixed sites and ten-fold cross-validation was used for home sites. **
City
Modeling region radius (km)
Number of monitors
AQS and fixed sites
Home sites




H/O
C/S




NOx
Baltimore









Los Angeles









San Francisco









New York









Salt Lake City









Ann Arbor









Winston-Salem









Chicago









St. Paul









NO2
Baltimore









New York









San Francisco









Los Angeles









Salt Lake City









Winston-Salem









Ann Arbor









Chicago









St. Paul









O3
Baltimore









New York









San Francisco









Los Angeles









Salt Lake City









Winston-Salem









Ann Arbor









Chicago









St. Paul









PM2.5
Baltimore









New York









San Francisco









Los Angeles









Salt Lake City









Winston-Salem









Ann Arbor









Chicago









St. Paul









A – AQS, F – Fixed, H/O – Home outdoor, C/S – Community Snapshot,  – Regression-based R-squared,  – MSE-based R-squared



**Table 30. 10-fold cross-validated R2 and RMSE by year for national NO2 model. All metrics are on the square root scale (sqrt(ppb)).**
Year












R2

























Year












R2

























Year












R2


























**Table 31. 10-fold cross-validated R2 and RMSE by year for national satellite-based NO2 model. All metrics are on the square root scale (sqrt(ppb)).**

**Table 32. 10-fold cross-validated R2 by year for national PM10 model. All metrics are on the square root scale (sqrt(µg/m3)).**

**Table 33. 10-fold cross-validated R2 by year for national PM2.5 model. All metrics are on the square root scale (sqrt(µg/m3)). Year 2000 published in Sampson et al, Atmospheric Env, 2013.22**


**Table 34. Cross-validated R2 and RMSE for EC, OC, Si, and S PM2.5 Components. All metrics are on the square root scale. Published in Bergen et al, EHP 2013.23**

**Table 35. Cross-validation statistics of the historical PM2.5 models for 1999-2010 by year and region.**





<!--
a. FRM = Federal Reference Method; IMPROVE = Interagency Monitoring of Protected Visual Environment; CASTNet = Clean Air Status and Trends Network; WBAN = Weather-Bureau-Army-Navy
b. Number of sites (Number of observations when different from the number of sites)
c. Annual averages from 1999 through 2010
-->

**Table 36. 10-fold cross-validated R2 on native and model scale for As, Du, Ni, SO4, So2, NO3, V, and Cr. * All components except for Cr were developed using covariates from Rev 5. Cr was built using Rev 4 covariates.**


**Table 37. Model performance (10-fold cross validated R2 and RMSE) for PM10-2.5 mass (µg/m3) and species concentrations (ng/m3) using land use regression (LUR). Table adapted from Zhang et al, Under review at EHP, 2013.24**



**Table 38. Leave-one-out cross validation RMSE of PM2.5 using “Pragmatic Model” at all sites and at fixed sites on native scale (ug/m3). * N is the number of sites used for modeling. Modified from Table 2 in Sampson et al, Atmostpheric Environment, 2011. 25**




**Table 39. 10-fold cross-validation of National Spatiotemporal PM2.5 Model. These validation statistics are produced automatically as an output of this model. See code for additional details (step4_national_CV.R)**


**Table 40. Cross-validation measures of predictive accuracy for site means at monitoring locations for likelihood-based exposure models of PM2.5 in the Puget Sound.  Leave-one-out cross-validation was used for AQS and Historical Nephelometer sites and ten-fold cross-validation was used for RAD monitor sites.  R2reg represents the regression R2.**



## J.  National Spatiotemporal PM2.5 Modeling Regions


**Figure. Participant locations and modeling region (left), Monitoring locations (right)**

## K.  Database location tables

Preferred table naming conventions:
For batches of participant locations: `<study>_<yyyymmdd>_location_tbl`

**Table 41. Location table names with native id patterns**


<!-- 
Table Name
native_id example
Native id pattern
Contents
actb2_location_tbl
ACT1001_0201
<study><ppt_id>_<batch><#>
ACT addresses, batch 2
actb3_location_tbl
ACT1001_0301
<study><ppt_id>_<batch><#>
ACT addresses, batch 3
actb4_location_tbl
ACT1002_0401
<study><ppt_id>_<batch><#>
ACT addreses, batch 4
actsnap_location_tbl
001A
<cluster><position>
ACT snapshot addresses
agency_location_tbl

<state & county fips><unique>
Air Agency monitoring locations
brfss_location_tbl
98001_0304012022c
<zip>_<id>
BRFSS study locations
ccarc_location_tbl
ccarc_000000
<study>_< id>
CCAR Collaborative study grid points
ccarflightpath_location_tbl
ccarflightpath_1
<study>_< id>
LAX flightpath ogawa monitoring locations
ccarp1_location_tbl
ccarp1a0000001
<study>< id>
CCAR Project 1 Ogawa and mobile monitoring locations
ccarp5_location_tbl
ccarp5_400
<study>_< id>
CCAR Project 5 participant home monitoring locations
cf2_location_tbl
cf2_010010204003000
<study><ppt_id>
Cystic fibrosis locations, batch 2
cf_location_tbl
cf110010077031003
<study><ppt_id>
Cystic fibrosis locations
chsaq_location_tbl
chsaq060370016
<study><ppt_id>

cohort_act_location_tbl
1001-1
<ppt_id>_<#>
ACT addresses, batch 1
cohort_chs_location_tbl
3000028-1
<ppt_id>_<#>

cohort_classic_location_tbl
classic3010007-01
<study><ppt_id>-<#>
MESA classic participant locations (Rev 12 or earlier)
cohort_fn_location_tbl
NRFam3110044-01
<study><ppt_id>-<#>
MESA Family & New REcruits participant locations (Rev 12 or earlier)
cohort_ln_gem_location_tbl
GEM110001-01
<study><ppt_id>-<#>
GEMS home locations, from LexisNexis
cohort_omega_location_tbl
omega10007-01
<study><ppt_id>-<#>
Omega participant locations
cohort_sister_hist_location_tbl
H1000010001
H<ppt_id><ind><ind><ind><ind>
Childood and longest-lived sister locations that don’t coincide with current
cohort_sister_location_tbl

<ppt_id><ind><ind><ind><ind>
Current sister study locations
cohort_sister_two_location_tbl
T6000020011
T<ppt_id>
Two Sister Study locations
cohort_spiro_location_tbl
spiro_A001000-0

Spiromics locations at baseline
cohort_va_location_tbl
va0000
<study><id>
VA study nearest intersections
cohort_whi_location_tbl
whi01000021
<study><unique>
Original WHI locations
consortium_regards_location_tbl
100012_1
<ppt_id>_<#>
REGARDS locations to be used for consortium project
consortium_sister_location_tbl
s1000011010
<study><ppt_id>
Sister Study locations provided recently
dichot_location_tbl
dichot2032

Dichot monitoring locations
fixed_location_tbl
B001

MESA Air fixed sites
gems_location_tbl
gems_110001-1
<study>_<ppt_id>-<#>
GEMS study locations
grid_100m_location_tbl
grid_100m_1
grid_<resolution>_<#>

grid_50m_location_tbl
CA5_50m_0
<stateplane>_<resolution>_<#>
Fine grid locations in MESA cities
grid_deeds_50m_location_tbl
grid_50m_10
grid_<resolution>_<#>
Fine grid locations covering Duwamish study area
grid_location_tbl
B_0001

1km, 2km, and 500m grid locations coverin g MESA modeling regions
grid_nation_25km_location_tbl
ALE_25km_13451
<stateplane>_<resolution>_<#>
National grid
grid_ps_location_tbl
PS_1000_1
<region>_<resolution>_<#>
Puget Sound grid
hr0287_pa_locations_location_tbl
pghcty001


ipn_location_tbl


Locations of the Inhalable Particle Network
ivf_location_tbl
ivf_0005814

IVF study locations
massblocks_location_tbl
250010102062101a001


mesa_2019_location_tbl
classic3010007-09
<stdy><ppt_id>-<#>
MESA Classic home locations, from 2019 update
met_location_tbl
0J4

Locations of met stations from NOAA
monitoring_act_location_tbl
ACTV001

ACT volunteer and home monitoring participant locations
monitoring_deeds_location_tbl


DEEDS monitoring locations
monitoring_mesa_location_tbl


MESA Home monitoring locations
monitoring_mesa_pilot_location_tbl
wilton_001

MESA IAr pilot Ogawa monitoring locations
monitoring_norris_location_tbl
norris_A

Ear;y 90’s ogawa-like monitoring
monitoring_panel_location_tbl
panel_101

1999 panel-study home monitoring locations
monitoring_rad_location_tbl
ACTV001

Remote Air Data monitoring locations, including MESA Air R56
monitoring_spiro_location_tbl
spiro_A01A
<spiro>_<ciy><site>
SPIROMICS homes monitoring locations
monitoring_yesler_location_tbl


Yesler Terrace monitoring locations
nhs2_location_tbl
NHS20000001

Nurse’s Health Study home locations
nomas_location_tbl
nomas_00001

NOMAS participant locations
nyccas_location_tbl
nyccas10023

New York City Communicaty Air Study monitoring locations
oakmonitors_location_tbl
oakmonitor_00002A

Oakland monitoring locations (external project, no monitoring data in database)
oakroads_location_tbl
oakroad_000001

Oakland on-road locations
presto_location_tbl
10201-01

PRESTO residential locations
pscaa_location_tbl


Pugest Sound Clean Air Agency monitoring locations, may not be included in Agency dataset
psid2015_location_tbl
psid2015_010010201002023c


psid_location_tbl
010010201002023C


ros_location_tbl
ros_1

Religious Orders Study locations
rush_location_tbl
rush_1_1


sister_test_location_tbl
s2041370100

?
spiro_fu_location_tbl
spiro0001-1


tract2000_location_tbl
06025010100c


tract2010_location_tbl
1E+09


whicap_location_tbl
whicap_000001


whi_2019_location_tbl
whi01000017-01


-->


## L.  ACT Spatiotemporal PM2.5 Modeling Regions and Temporal Monitoring Coverage

**Figure. Participant locations and modeling region (left), Monitoring locations (right)**

 

**Figure. Temporal Coverage of ACT PM2.5 ST Model Monitoring Data**



## M.  SPIROMICS Indoor Exposure Modeling Predictions

**Table 42. Indoor exposure modeling participants, dates, and cities**

**Table 43. Census data filled via ACS 5-year estimates**


**References for Census data:**

- Eberwein, Kris. 2019. blscrapeR: An API Wrapper for the Bureau of Labor Statistics (BLS) [R package, version 3.2.0]. https://CRAN.R-project.org/package=blscrapeR

- U.S. Bureau of Labor Statistics. Consumer Price Index - All Urban Consumers (Current Series). Retrieved from https://download.bls.gov/pub/time.series/cu/

- U.S. Census Bureau. Selected housing characteristics, 2009-2013 American Community Survey 5-year estimates. Retrieved from https://data.census.gov/cedsci/table?q=United%20States&tid=ACSDP5Y2018.DP05&hidePreview=false


**Table 44. Additional sources for building ages by web domain**

<!--
References for building age:
Apartable, Inc. 2020. Apartable. https://apartable.com/

Community Housing Partnership [San Francisco]. 2020. Chp-sf.org. https://chp-sf.org

CoStar Group, Inc. 2020. Apartments.com. https://www.apartments.com/

Foundation Housing. 2020. https://foundationhousing.com/

MyLife.com, Inc. 2020. MyLife. https://www.mylife.com

National Association of Realtors and Move, Inc. 2020. Realtor.com. https://www.realtor.com

Property Research Partners LLC. 2020. PropertyShark.com. https://www.propertyshark.com

Redfin. 2020. Redfin.com. https://www.redfin.com

San Francisco Planning Department. 2020. San Francisco Planning GIS Tools. https://sfplanninggis.org

Trulia, LLC. 2020. Trulia.com. https://www.trulia.com

Zillow, Inc. 2020. https://www.zillow.com
-->
