--- 
title: "Data Organization and Operating Procedures: Revision 14, 2020"
author: "MESA Air"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
#bibliography: [book.bib, packages.bib]
#biblio-style: apalike
#link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---



<!--
## Prerequisites

This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2$.

The **bookdown** package can be installed from CRAN or Github:

```{r eval=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```
-->

# Overview/Purpose and Included Data {.unnumbered}

The purpose of this document is to describe the collection, processing, and management of exposure data for the Multi-Ethnic Study of Atherosclerosis and Air Pollution (MESA Air) and associated environmental epidemiology studies.  The primary aims are: 1) to record the treatment of all of the Kaufman Lab’s environmental monitoring data prior to its upload to the Exposure Assessment Core’s (EAC) database; 2) to describe the content and processing of third-party (e.g., Air Quality Systems, NYCCAS) data; and 3) to describe the data request process.  Health data are collected and stored at study-specific coordinating centers, and documentation for these data handling procedures can be found in a separate Standard Operating Procedure (SOP) document.  The EAC does not fill data requests for health data.  We are currently distributing data from Revision 14 (Rev 14) of the EAC Database.  The data available in Rev 14 include:

## Location data
Location identifiers for monitoring sites and participant homes include: county according to the 2000 Census, state, metropolitan statistical area as of the year 2000 and CBSA as of the year 2010, census tract, block group, and block according to years 2000 and 2010 censuses, projected coordinates [x,y] referenced to the national US Conical Lambert projection in meters, latitude and longitude in decimal degrees.

### Residential Locations
- Addresses for participants in the Women’s Health Institute Observational Study and Clinical Trial (WHI-OS and CT) (not participant-linked), updated in 2019
- Addresses for participants in the Cardiovascular Health Study (CHS) (not time resolved)
- Addresses for NOMAS (not time resolved)
- Time-resolved address histories for the Sister study plus baseline and secondary (both at baseline), childhood, and longest-lived addresses for participants in the Sister and Two Sister Studies
- Locations of intersections near BREATH participant residences
- Time-resolved address histories for MESA Air participants
- Time-resolved address histories for SPIROMICS Air participants
- Time-resolved address histories for ACT-AP participants
- Addresses for GEMS participants
- Addresses for REGARDS participants
- Air Monitoring Locations and Weather Stations
- New York City Community Air Survey (NYCCAS) monitoring sites
- Inhalable Particle Network (IPN) sites
- AQS (state and local) and IMPROVE (federal) monitoring network sites
- MESA Air monitoring sites
- Yesler Terrace monitoring sites
- Diesel Exhaust Exposure in the Duwamish Study (DEEDS) monitoring sites
- CCAR Project 1 mobile monitoring routes in Baltimore, MD and passive badge sites in Atlanta, GA; Baltimore, MD; Winston-Salem, NC; and Los Angeles, CA
- CCAR Project 5 monitoring sites
- SPIROMICS Air monitoring sites
- LAX flightpath monitoring locations
- NOAA meteorological monitoring stations throughout the continental US
- PM Center Panel Study monitoring locations
- ACT-AP monitoring locations, including participant homes, snapshot locations, and mobile monitoring stop locations
- Monitoring locations in Pittsburgh and Philidelphia associated with the AsthmaNet study

### Other Locations
- Locations for grids of points in Los Angeles, San Francisco, Salt Lake City, New York City, Ann Arbor, Winston-Salem, Baltimore, Chicago, Minneapolis-St. Paul, and Memphis metropolitan areas to facilitate the production of maps illustrating area-wide surfaces (regional grids) and small-scale variations (fine-scale grids) of model predictions

- A regional grid for Seattle

- Two regional grids for Puget Sound

- Fine-scale grid points in Seattle covering the area relevant to DEEDS and another covering the downtown area

- Fine-scale grid and on-road points covering Oakland

- Locations for a large-scale grid of points nationwide, also to facilitate map production

- Grid point locations used in the CCAR Collaboration Project

- Year 2010 Census Tract centroids

## Address History
- All available time-resolved address histories for all MESA and MESA Air participants (with the exception of 11 MESA participants who explicitly declined to participate in MESA Air)) from 1980 through the end of Exam 5 in the MESA Air extended region.  “At exam” addresses are identified for the residences of MESA Air participants on the dates of clinical exams, Computed Axial Tomography (CT) scans, magnetic resonance imaging (MRI) scans, ultrasound scans, and spirometry
   
- All available time-resolved address histories for SPIROMICS Air participants
   
- All available time-resolved address histories for ACT participants
   
- All available time-resolved address histories for Sister Study participants

## Federal, State, and Local Agency Monitoring data
AQS, Speciation Trends Network (STN), and IMPROVE monitoring data are available throughout the lower 48 United States and Hawai’i.  The years for which data are available for specific pollutants are variable, as regulatory needs have changed over time.  The last date for which data are available varies by location and depends on the diligence with which agencies report updates.  In general, AQS and STN data are considered up-to-date through mid-2019 for most locations.  IMPROVE data are available from March 1988 through December 2019 for PM2.5 and its species.  Specific availability by pollutant is as follows:
   
- AQS monitoring data for NO2, NOX, SO2, O3, and CO beginning in 1980
   
- AQS monitoring data for PM10 beginning in 1983 and IMPROVE monitoring beginning in 1999
   
- AQS monitoring data for PM2.5 beginning in 1999, IMPROVE monitoring data beginning in 1988
   
- AQS monitoring data for sulfate (SO42-) and nitrate (NO3-) beginning in 2000
   
- STN monitoring data for elemental carbon and organic carbon (EC/OC) beginning February 2000, IMPROVE monitoring data for EC/OC beginning March 1988  
   
- STN and IMPROVE monitoring data for selected elemental species (aluminum, arsenic, bromine, cadmium, calcium, chromium, cobalt, copper, iron, potassium, manganese, sodium, silicon, selenium, sulfur, nickel, vanadium, and zinc) beginning in 1988
   
- IPN monitoring data for PM2.5, PM15, PM15-2.5, and PM30 between 1979 and 1982

## Air quality data collected through MESA Air and related studies
- PM2.5, PM2.5 species, NOX, NO2 and O3  data collected as part of MESA Air and the Health Effects Institute (HEI) / National Particle Components Toxicity (NPACT) study
   
- PM2.5, NOX, NO2 and O3 monitoring data collected as part of the SPIROMICS Air Study
   
- PM2.5 and NOX monitoring data collected as part of DEEDS
   
- NOX monitoring data collected in Yesler Terrace
   
- NOX monitoring data collected under the LAX approach flightpath
   
- PM2.5, PM10, PM10-2.5, associated elemental species, and endotoxin monitoring data collected as a part of the MESA Coarse PM Study
   
- NOX and O3 Ogawa badge data collected at ‘fuzzy points’ in Atlanta, Baltimore, LA, Winston-Salem, and St. Paul by CCAR Project 1
   
- NOX, O3, and VOC badge data collected at residential locations and in vehicles in Winston-Salem and LA as part of CCAR Project 5
   
- PM2.5, NOX, NO2 and O3 monitoring data collected as part of the ACT-AP Study

## Exposure model outputs – MESA and SPIROMICS regions
- PM2.5, NOX, NO2, and O3 predictions for MESA Air participants’ addresses throughout the MESA Air areas for the years 1999 – 2018 at 2-week resolution
   
- PM2.5, NOX, NO2, and O3 predictions for SPIROMICS Air participants’ addresses throughout the SPIROMICS Air areas for the years 1999 – 2018 at 2-week resolution
   
- Indoor PM2.5, NOX, NO2, and nicotine for the subset of SPIROMICS addresses with Home Information Questionnaire data
   
- LAC predictions for MESA Air participants’ addresses in the MESA Air areas representing long-term exposure (predictions averaged over 2006 – 2008) and at two-week resolution (2005 – 2009)
   
- Land use regression predictions for PM10-2.5 and silicon, copper, zinc, and phosphorus in the coarse fraction for MESA Air participants’ addresses in the MESA Coarse Study monitoring areas (Chicago, Winston-Salem, and St. Paul)

## Exposure model outputs – National Models (Continental US, Annual Averages)
- PM2.5 predictions for each year from 1999 – 2015 at MESA Air, SPIROMICS Air, ACT-AP, WHI-OS, Sisters, Two Sisters and CHS participants’ residential locations
   
- PM2.5 predictions for each year from 1980 – 2010 at MESA Air, WHI-OS, Sisters, and Two Sisters participants’ residential locations from an annual spatio-temporal model (“historical PM2.5 model”)
   
- EC, OC, arsenic, silicon, sulfur, chromium, copper, SO42-, SO2, nickel, nitrate, and vanadium predictions for 2009 at MESA Air and WHI-OS participants’ residential locations
   
- PM10 predictions for each year from 1990 – 2016 for MESA Air, SPIROMICS Air, ACT-AP, WHI-OS, Sisters, Two Sister, and CHS participants’ residential locations
   
- NO2 predictions for each year from 1990 – 2014 for MESA Air, SPIROMICS Air, ACT-AP, WHI-OS, Sisters, and Two Sister participants  
   
- NO2 predictions for the year 2006 at census block centroids from the model developed by Novotny et. al.1  These predictions are available for all locations in the continental US.
   
- K-means cluster predictions

## Exposure estimates based on AQS data
- Time series data of PM2.5 for each MESA Air and SPIROMICS Air area designated for acute analyses
   
- Specified “long-running” monitors for long-term ‘nearest monitor’ analyses for PM2.5
   
- Cascading nearest monitor assignments (described in more detail later), for more unusual analyses

## Meteorological data
- Visibility, temperature, wind speed, wind direction, humidity, sea level pressure, station-level pressure and ceiling height data at the daily time scale at meteorological stations throughout the nation from the years 1979 – September 2019
   
- The meteorological data is downloaded from the following NOAA source: https://www.ncei.noaa.gov/data/local-climatological-data/access/

## Geographically-linked data
- Geographic covariate values 
        
- USGS aerial photography-based land use in buffers, year 2006 satellite-based land use in buffers, impervious surface, normalized difference vegetative index (NDVI), distance to features, emissions in buffers, sum of road lengths in a buffer, sum of truck route lengths in a buffer, counts of intersections in buffers, population in buffers, and elevation nationally 
        
- Distance to city hall for some locations in the MESA Air regions
        
- Distance to nearest residual oil source, sums of oil emissions in buffers, nearest bus route, and sum of bus routes in buffers for the New York City area
        
- Urban topography for locations in New York City and Chicago
   
- Selected census variables for all block groups, blocks, and tracts in the lower 48 United States for both Census 2000 and Census 2010
   
- Average column NO2 for the year 2006 at census block centroid as measured by satellite image processing 
   
- Average column NO2 for a Moore neighborhood of pixels near each location in the continental US for the years 2005 – 2007
   
- CALINE3QHCR dispersion model averages of the years 2004 – 2006 for monitoring locations and MESA Air participant addresses 
   
- Vehicle emissions model outputs (MOVES data) by month for the years 1990 and 1999 – 2012.

Additional data will be added in future releases of the database.  Planned updates are slated to include:
   
- Additional updates of existing models (e.g., national PM2.5, national NO2, likelihood-based PM2.5), are expected, both to incorporate additional AQS data not currently available and to reflect improvements to modeling methodology.
   
- National scale spatio-temporal models
   
- MESA Air address updates
   
- Updated bus and truck routes

Database revisions are planned to occur approximately once per year.  If the available data does not satisfy the needs of a particular analysis, data users are encouraged to contact the EAC as soon as possible to negotiate new data’s inclusion in an upcoming revision.
